remote_theme: Memerator/Jekyll-Template

# Title of the site.
# Shows up in navbar and embeds
title: Memerator

# Nav Bar elements.
nav:
- title: <i class="fas fa-home"></i> Home
  url: /
- title: Skyblock
  url: skyblock
- title: SkyGrid
  url: skygrid
- title: CaveBlock
  url: caveblock
- title: AcidIsland
  url: acidisland
- title: OneBlock
  url: oneblock

url: https://memerator.github.io/Skyblock
